// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/devtron-labs/telemetry/api"
	"github.com/devtron-labs/telemetry/internal/logger"
	"github.com/devtron-labs/telemetry/internal/util"
	"github.com/devtron-labs/telemetry/pkg/telemetry"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugardLogger()
	client := logger.NewHttpClient()
	posthogConfig, err := util.GetPosthogConfig()
	if err != nil {
		return nil, err
	}
	optOutConfig, err := telemetry.GetOptOutConfig()
	if err != nil {
		return nil, err
	}
	telemetryServiceImpl := telemetry.NewTelemetryServiceImpl(sugaredLogger, client, posthogConfig, optOutConfig)
	restHandlerImpl := api.NewRestHandlerImpl(sugaredLogger, telemetryServiceImpl)
	muxRouter := api.NewMuxRouter(sugaredLogger, restHandlerImpl)
	app := NewApp(muxRouter, sugaredLogger)
	return app, nil
}
